version: '3.9'

services:

# docker run -p 8761:8761 khushwinderdocker/microservices-naming-server:0.0.1-SNAPSHOT
  naming-server:
    image: khushwinderdocker/microservices-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

#docker run -p 8765:8765 khushwinderdocker/microservices-api-gateway:0.0.1-SNAPSHOT
  api-gateway:
    image: khushwinderdocker/microservices-api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
      spring.zipkin.baseUrl: http://zipkin-server:9411/

  currency-exchange:
    image: khushwinderdocker/microservices-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
      spring.zipkin.baseUrl: http://zipkin-server:9411/

  currency-converter:
    image: khushwinderdocker/microservices-currency-conversion-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
      spring.zipkin.baseUrl: http://zipkin-server:9411/


  #docker run -p 9411:9411 openzipkin/zipkin:latest

  zipkin-server:
    image: openzipkin/zipkin:latest
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - currency-network
    restart: always #Restart if there is a problem starting up

networks:
  currency-network:
